apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp-deployment
  labels:
    app: myreactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      labels:
        app: myreactapp
    spec:
      containers:
      - name: myreactapp-container
        image: scott2srikanth/myfsdcc_pipeline
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myreactapp-service
spec:
  type: LoadBalancer
  selector:
    app: myreactapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000